package tests;

import clients.STTClient;
import clients.TTSClient;
import clients.VoiceCloneClient;
import org.testng.annotations.Test;
import utils.FileUtils;
import utils.TranscriptUtils;

import java.io.File;

import static org.testng.Assert.assertTrue;

public class VoiceCloneE2ETest {

    private static final String REFERENCE_AUDIO_PATH = "src/test/resources/sample.mp3";
    private static final String SAMPLE_TEXT = "Hello, this is a sample text for step two.";
    private final VoiceCloneClient voiceCloneClient = new VoiceCloneClient();
    private final TTSClient ttsClient = new TTSClient();
    private final STTClient sttClient = new STTClient();

    @Test
    public void verifyVoiceCloneTtsAndSttJourney() {

//        Step 1: Create a voice clone using the reference audio.
        File referenceAudio = new File(REFERENCE_AUDIO_PATH);
        String uniqueDisplayName = "QA Voice Clone " + System.currentTimeMillis();
        String voiceId = voiceCloneClient.createVoiceClone(referenceAudio,uniqueDisplayName);

//         Step 1B: Verify that the newly created clone is visible through the GET API.
        voiceCloneClient.verifyVoiceCloneExists(voiceId);

//        Step 2: Generate speech using the cloned voice.
        byte[] generatedAudioBytes = ttsClient.generateSpeech(voiceId,SAMPLE_TEXT);
//        Save the generated audio temporarily, This file becomes the input to the STT API.
        File generatedAudioFile = FileUtils.saveAudioFile(generatedAudioBytes, "tts-output.wav");

//        Step 3: Transcribe the exact audio generated by the TTS API.
        String actualTranscript = sttClient.transcribeAudio(generatedAudioFile);
//        Compare the original TTS input text with the transcript returned by STT.
        double similarity = TranscriptUtils.calculateWordSimilarity(SAMPLE_TEXT, actualTranscript);

        System.out.println("Original text: " + SAMPLE_TEXT);
        System.out.println("STT transcript: " + actualTranscript);
        System.out.println("Transcript similarity: " + similarity * 100 + "%");

//        Checking: transcript is consistent with the audio
        assertTrue(
                similarity >= 0.80,
                "Transcript similarity is below the expected threshold."
                        + "\nExpected text: " + SAMPLE_TEXT + "\nActual transcript: " + actualTranscript + "\nSimilarity: " + similarity
        );
    }
}
